// YBÜ Antibiyotik Rehberi — veri kaynağı
// Kaynak: yogun-bakim-antibiyotik-kilavuzu-v5.xlsx
const DRUG_DATA = [
  {
    "slug": "piperasilin-tazobaktam",
    "kategori": "BETA-LAKTAMLAR",
    "kategoriKisa": "Beta-Laktamlar",
    "kategoriRenk": "blue",
    "grup": "Antipsödomonal Penisilin",
    "etken": "Piperasilin-Tazobaktam",
    "pazar": "Tazocin, Pipraks",
    "ozellikler": "Geniş spektrum; Gram-pozitifler, Gram-negatifler (Pseudomonas dahil) ve anaeroblar.",
    "endikasyon": "HAP/VAP, intraabdominal enfeksiyonlar, dikiş sızıntıları, komplike İYE.",
    "standartDoz": "Düşük/Standart Doz: 3.375 g q6h IV (Komplike İYE, pelvik enfeksiyonlar, hafif intraabdominal)\nYüksek Doz: 4.5 g q6h IV (HAP/VAP, febril nötropeni, ağır sepsis, Pseudomonas şüphesi)\n(Her iki doz için de 4 saatlik uzatılmış infüzyon PK/PD hedefini artırır)",
    "renalDoz": "CrCl >40: Doz ayarı gerekmez.\nCrCl 20-40: 3.375 g q6h veya 4.5 g q8h IV.\nCrCl <20: 2.25 g q6h veya 3.375 g q8h IV.\nHD/CRRT: 2.25 g q8h veya 3.375 g q12h IV.",
    "sinirlamalar": "ESBL üreten suşlara karşı monoterapi olarak güvensiz olabilir; MRSA, VRE ve atipik bakterilere etkisizdir.",
    "yanEtki": "Aşırı duyarlılık, lökopeni, trombositopeni (özellikle uzun süreli kullanımda).",
    "nefroSeviye": "Orta",
    "nefroNot": "Vankomisin ile sinerjik hasar!",
    "eliminasyon": "Renal (%70 oranında idrarla değişmeden atılır)"
  },
  {
    "slug": "sefepim",
    "kategori": "BETA-LAKTAMLAR",
    "kategoriKisa": "Beta-Laktamlar",
    "kategoriRenk": "blue",
    "grup": "4. Kuşak Sefalosporin",
    "etken": "Sefepim",
    "pazar": "Unisef, Maxipime",
    "ozellikler": "Geniş Gram-negatif spektrum (Pseudomonas dahil), iyi Gram-pozitif kapsama.",
    "endikasyon": "Nötropenik ateş, nozokomiyal pnömoni, sepsis.",
    "standartDoz": "Düşük Doz: 1-2 g q12h IV (Hafif-orta İYE, intraabdominal)\nYüksek Doz: 2 g q8h IV (Psödomonal enfeksiyonlar, nötropenik ateş, ağır VAP)",
    "renalDoz": "CrCl >50: Doz ayarı gerekmez.\nCrCl 30-50: 2 g q12h IV.\nCrCl 11-29: 2 g q24h IV.\nCrCl <11: 1 g q24h IV.\nCRRT: 2 g q12h IV.",
    "sinirlamalar": "Anaerobik etkinliği yoktur (Metronidazol eklenmelidir); MRSA, VRE, ESBL ve atipiklere etkisizdir.",
    "yanEtki": "Sefepim Ensefalopatisi (ajitasyon, miyoklonus, NCSE), ilaç ateşi.",
    "nefroSeviye": "Düşük",
    "nefroNot": "Renal birikimde nörotoksiktir",
    "eliminasyon": "Renal (Böbrek tübüler sekresyonuyla atılır)"
  },
  {
    "slug": "seftazidim-avibaktam",
    "kategori": "BETA-LAKTAMLAR",
    "kategoriKisa": "Beta-Laktamlar",
    "kategoriRenk": "blue",
    "grup": "Yeni Beta-Laktam/İnhibitör",
    "etken": "Seftazidim-Avibaktam",
    "pazar": "Zavicefta",
    "ozellikler": "KPC, OXA-48 ve ESBL üreten dirençli Gram-negatif çomaklar.",
    "endikasyon": "Dirençli Klebsiella/Pseudomonas sepsisleri, komplike intraabdominal enfeksiyonlar.",
    "standartDoz": "2.5 g q8h IV (2 saatlik infüzyon)",
    "renalDoz": "CrCl >50: Doz ayarı gerekmez.\nCrCl 31-50: 1.25 g q8h IV.\nCrCl 16-30: 0.94 g q12h IV.\nCrCl 6-15: 0.94 g q24h IV.\nCrCl <6: 0.47 g q24h IV.",
    "sinirlamalar": "Metallo-beta-laktamaz (NDM, VIM vb.) üreten bakterilere karşı tek başına tamamen etkisizdir (Aztreonam eklenmelidir).",
    "yanEtki": "Coombs testi pozitifliği, baş ağrısı, gastrointestinal intolerans.",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Renal (İdrarla değişmeden atılır)"
  },
  {
    "slug": "sefoperazon-sulbaktam",
    "kategori": "BETA-LAKTAMLAR",
    "kategoriKisa": "Beta-Laktamlar",
    "kategoriRenk": "blue",
    "grup": "Kombine Sefalosporin",
    "etken": "Sefoperazon-Sulbaktam",
    "pazar": "Sulperazon, Zonactam",
    "ozellikler": "Gram-negatifler (Pseudomonas, Acinetobacter dahil), Gram-pozitifler ve anaeroblar.",
    "endikasyon": "İntraabdominal sepsis, safra yolu enfeksiyonları, hastane kaynaklı pnömoni.",
    "standartDoz": "Düşük Doz: 2 g q12h IV (Sefoperazon bileşenine göre, standart intraabdominal/safra)\nYüksek Doz: 4 g q12h VEYA 2 g q6h IV (Günlük max 8 g'a kadar; ağır nozokomiyal sepsis, dirençli Acinetobacter veya Pseudomonas)",
    "renalDoz": "Sefoperazon için renal doz ayarı gerekmez (safra ile atılır). Ancak Sulbaktam birikimini önlemek için:\nCrCl 15-30: Max 2 g/gün sulbaktam (örn. 2g q12h 1:1 flakon).\nCrCl <15: Max 1 g/gün sulbaktam (örn. 1g q12h 1:1 flakon).",
    "sinirlamalar": "MRSA, VRE, Stenotrophomonas maltophilia'ya etkisizdir.",
    "yanEtki": "Disülfiram benzeri reaksiyon (alkol ile), hipoprothrombinemi (K vitamini eksikliğiyle kanama eğilimi).",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Dual (%70 Safra/Karaciğer, %30 Böbrekler)"
  },
  {
    "slug": "meropenem",
    "kategori": "BETA-LAKTAMLAR",
    "kategoriKisa": "Beta-Laktamlar",
    "kategoriRenk": "blue",
    "grup": "Karbapenem",
    "etken": "Meropenem",
    "pazar": "Meronem, Mopen",
    "ozellikler": "Son derece geniş spektrum; ESBL üreten Gram-negatifler, anaeroblar ve Gram-pozitifler.",
    "endikasyon": "Ağır intraabdominal sepsis, nozokomiyal pnömoni, menenjit.",
    "standartDoz": "Düşük Doz: 1 g q8h IV (Ağır intraabdominal sepsis, standart HAP/VAP)\nYüksek Doz: 2 g q8h IV (Akut bakteriyel menenjit, kafa travmasına bağlı santral enfeksiyonlar, dirençli Pseudomonas/Acinetobacter sepsisi; 3 saatlik uzatılmış infüzyon)",
    "renalDoz": "CrCl >50: Doz ayarı gerekmez.\nCrCl 26-50: 1-2 g q12h IV.\nCrCl 10-25: 500 mg - 1 g q12h IV.\nCrCl <10: 500 mg q24h IV.\nCRRT: 1 g q12h IV.",
    "sinirlamalar": "MRSA, VRE, Stenotrophomonas maltophilia ve metalo-karbapenemaz üreten suşlara etkisizdir.",
    "yanEtki": "Nöbet eşiğini düşürme (İmipeneme göre belirgin az), döküntü, trombositopeni.",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Renal (%70 glomerüler filtrasyonla değişmeden)"
  },
  {
    "slug": "imipenem-silastatin",
    "kategori": "BETA-LAKTAMLAR",
    "kategoriKisa": "Beta-Laktamlar",
    "kategoriRenk": "blue",
    "grup": "Karbapenem",
    "etken": "İmipenem-Silastatin",
    "pazar": "Tienam",
    "ozellikler": "Geniş Gram-pozitif, Gram-negatif ve anaerob etkinlik.",
    "endikasyon": "Polimikrobiyal ağır sepsisler, dirençli bakteriyel enfeksiyonlar.",
    "standartDoz": "Düşük Doz: 500 mg q6h IV (Standart sepsis ve intraabdominal enfeksiyonlar)\nYüksek Doz: 1 g q8h VEYA 1 g q6h IV (Dirençli Gram-negatif enfeksiyonlar, ağır şok; nöbet riski nedeniyle menenjitte meropenem tercih edilir)",
    "renalDoz": "CrCl >90: Doz ayarı gerekmez.\nCrCl 50-90: 500 mg q8h IV.\nCrCl 15-50: 250 mg q8h veya 500 mg q12h IV.\nCrCl <15: 250 mg q12h IV.\nCRRT: 500 mg q12h IV.",
    "sinirlamalar": "Meropeneme benzer; ancak nöbet riski taşıdığı için SSS enfeksiyonlarında (menenjit) kullanılmamalıdır.",
    "yanEtki": "Yüksek nöbet riski (%0.9-3), bulantı, kusma (özellikle hızlı infüzyonda).",
    "nefroSeviye": "Düşük-Orta",
    "nefroNot": "Silastatin renal proksimal tübülleri korur",
    "eliminasyon": "Renal (%70 oranında böbreklerden süzülür)"
  },
  {
    "slug": "vankomisin",
    "kategori": "GLİKOPEPTİTLER / LİPOPEPTİTLER / LİNEZOLİD",
    "kategoriKisa": "Glikopeptit / Lipopeptit / Linezolid",
    "kategoriRenk": "purple",
    "grup": "Glikopeptit",
    "etken": "Vankomisin",
    "pazar": "Vancocin, Edicin",
    "ozellikler": "Sadece Gram-pozitif spektrum (MRSA, Ampisiline dirençli Enterokoklar).",
    "endikasyon": "MRSA sepsisi, kateter enfeksiyonları, MRSA VAP, C. difficile koliti (oral).",
    "standartDoz": "Düşük Doz: 15-20 mg/kg q12h IV (Klasik MRSA hedefi: Çukur düzeyi 15-20 mcg/mL)\nYüksek Doz: 25-30 mg/kg Tek Doz Yükleme, ardından TDM eşliğinde yüksek idame (Kritik sepsis, menenjit, endokardit, kemik-eklem enfeksiyonları)",
    "renalDoz": "CrCl >50: Standart q12h.\nCrCl 20-50: q24h veya q48h.\nCrCl <20: Terapötik İlaç İzlemi (TDM) ve serum düzeyine göre dozlanır.\nCRRT: 500 mg - 1 g q24-48h (TDM ile).",
    "sinirlamalar": "Tüm Gram-negatiflere tamamen etkisizdir. Akut böbrek hasarı olanlarda TDM yapılmaksızın kullanılması tehlikelidir.",
    "yanEtki": "Nefrotoksisite (doz ve süre bağımlı), Red Man Sendromu (hızlı infüzyonda), lökopeni.",
    "nefroSeviye": "Yüksek",
    "nefroNot": "Çukur düzeyi >20 mcg/mL ise hasar katlanır",
    "eliminasyon": "Renal (%80-90 glomerüler filtrasyonla idrardan)"
  },
  {
    "slug": "teikoplanin",
    "kategori": "GLİKOPEPTİTLER / LİPOPEPTİTLER / LİNEZOLİD",
    "kategoriKisa": "Glikopeptit / Lipopeptit / Linezolid",
    "kategoriRenk": "purple",
    "grup": "Glikopeptit",
    "etken": "Teikoplanin",
    "pazar": "Targocid",
    "ozellikler": "Dar spektrumlu Gram-pozitif kapsama (MRSA ve Ampisiline duyarlı Enterokoklar dahil). Vankomisine göre çok daha uzun yarı ömre sahiptir.",
    "endikasyon": "Kateter ilişkili enfeksiyonlar, deri-yumuşak doku enfeksiyonları, MRSA sepsisi, kemik-eklem enfeksiyonları.",
    "standartDoz": "Düşük Doz: Yükleme 6 mg/kg q12h (3 doz), ardından 6 mg/kg q24h IV\nYüksek Doz: Yükleme 12 mg/kg q12h (3-5 doz), ardından 12 mg/kg q24h IV",
    "renalDoz": "İlk 3 gün (veya yükleme fazında) doz azaltılmaz.\nCrCl 40-60: İdame dozu %50 azaltılır veya 48 saatte bir (q48h) verilir.\nCrCl <40: İdame dozu normalin 1/3'üne azaltılır veya 3 günde bir (q72h) verilir.\nHD/CRRT: Normal yükleme, idame dozu 3 günde bir verilir.",
    "sinirlamalar": "Gram-negatif bakteriler, anaeroblar, VRE (özellikle VanA fenotipi dirençlidir).",
    "yanEtki": "Trombositopeni (özellikle yüksek dozlarda), aşırı duyarlılık (ilaç ateşi), döküntü, geçici karaciğer enzim yüksekliği.",
    "nefroSeviye": "Düşük",
    "nefroNot": "Vankomisine göre belirgin derecede daha az nefrotoksiktir",
    "eliminasyon": "Renal (%90'ı değişmeden idrarla atılır; eliminasyon yarı ömrü 100-150 saattir)"
  },
  {
    "slug": "daptomisin",
    "kategori": "GLİKOPEPTİTLER / LİPOPEPTİTLER / LİNEZOLİD",
    "kategoriKisa": "Glikopeptit / Lipopeptit / Linezolid",
    "kategoriRenk": "purple",
    "grup": "Lipopeptit",
    "etken": "Daptomisin",
    "pazar": "Cubicin",
    "ozellikler": "Gram-pozitif bakteriler (MRSA, VRE - Vancomycin Resistant Enterococci).",
    "endikasyon": "Komplike cilt ve yumuşak doku enfeksiyonları, sağ taraf endokarditi, VRE sepsisi.",
    "standartDoz": "Düşük Doz: 6 mg/kg q24h IV (Komplike deri ve yumuşak doku enfeksiyonları)\nYüksek Doz: 8-12 mg/kg q24h IV (MRSA Bakteremisi, sağ taraf endokarditi; kas toksisitesine karşı haftalık CK takibi şarttır)",
    "renalDoz": "CrCl >=30: Doz ayarı gerekmez.\nCrCl <30: Aynı doz 48 saatte bir (q48h) uygulanır.\nHD/CRRT: Aynı doz 48 saatte bir verilir.",
    "sinirlamalar": "Sürfaktan ile inaktive olduğu için pnömonilerde (VAP dahil) KESİNLİKLE etkisizdir.",
    "yanEtki": "Miyopati (Kreatin Kinaz - CK takibi şarttır!), periferik nöropati, eozinofilik pnömoni.",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Renal (%80 idrarla değişmeden atılır)"
  },
  {
    "slug": "linezolid",
    "kategori": "GLİKOPEPTİTLER / LİPOPEPTİTLER / LİNEZOLİD",
    "kategoriKisa": "Glikopeptit / Lipopeptit / Linezolid",
    "kategoriRenk": "purple",
    "grup": "Oksazolidinon",
    "etken": "Linezolid",
    "pazar": "Zyvoxid, Lizolid",
    "ozellikler": "Gram-pozitif spektrum (MRSA, VRE, penisiline dirençli pnömokoklar).",
    "endikasyon": "MRSA/VRE pnömonisi, dirençli yumuşak doku enfeksiyonları, kateter sepsisi.",
    "standartDoz": "Düşük Doz: 600 mg q12h IV veya PO\nYüksek Doz: 600 mg q12h IV veya PO",
    "renalDoz": "Böbrek yetmezliğinde doz ayarlaması gerekmez.\nHD/CRRT: Doz ayarı gerekmez (hemodiyaliz sonrasında verilmesi tercih edilir).",
    "sinirlamalar": "Gram-negatif aerob ve anaerob bakterilere karşı tamamen etkisizdir.",
    "yanEtki": "Trombositopeni (özellikle >10-14 gün kullanımda), laktik asidoz, periferik/optik nöropati (uzun vadede), Serotonin Sendromu (SSRI ile).",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Hepatik dışı oksidasyon (%70) ve kısmen renal atılım."
  },
  {
    "slug": "kolistin",
    "kategori": "POLİMİKSİNLER / AMİNOGLİKOZİTLER / TİGESİKLİN",
    "kategoriKisa": "Polimiksin / Aminoglikozit / Tigesiklin",
    "kategoriRenk": "amber",
    "grup": "Polimiksin",
    "etken": "Kolistin",
    "pazar": "Colimycin, Colis",
    "ozellikler": "Dirençli Gram-negatifler (Pseudomonas, Acinetobacter, Klebsiella OXA-48/KPC).",
    "endikasyon": "Çoklu dirençli Gram-negatif sepsisleri, ventilatör ilişkili pnömoni (IV + inhaler).",
    "standartDoz": "9 Milyon IU IV Yükleme, 12 saat sonra 2x4.5 Milyon IU IV İdame",
    "renalDoz": "CrCl >50: 4.5 MIU q12h IV.\nCrCl 30-50: 3.5 MIU q12h IV.\nCrCl 10-29: 2.5 MIU q12h IV.\nCrCl <10: 1.5 - 2 MIU q12h IV.\nCRRT: 2.25 MIU q12h IV.",
    "sinirlamalar": "Proteus, Providencia, Serratia ve Gram-pozitif bakterilere karşı tamamen etkisizdir.",
    "yanEtki": "Ağır nefrotoksisite (tübüler hasar), nöromüsküler blokaj (akut apne riski), paresteziler.",
    "nefroSeviye": "Yüksek",
    "nefroNot": "Ort. serum düzeyi >2 mg/L ise AKI fırlar",
    "eliminasyon": "Renal (Aktif ilaç böbrekten, inaktif CMS böbrek dışı)"
  },
  {
    "slug": "polimiksin-b",
    "kategori": "POLİMİKSİNLER / AMİNOGLİKOZİTLER / TİGESİKLİN",
    "kategoriKisa": "Polimiksin / Aminoglikozit / Tigesiklin",
    "kategoriRenk": "amber",
    "grup": "Polimiksin",
    "etken": "Polimiksin B",
    "pazar": "Standart ticari adı belirtilmemiştir",
    "ozellikler": "MDR/XDR Gram-negatifler (CRAB, CRPA, KPC/OXA-48/NDM üreten Enterobacteriaceae); LPS/Lipid A'ya bağlanıp membranı bozar, dolaşımdaki endotoksini de nötralize eder. Kolistin'in aksine doğrudan aktif madde olarak verilir (ön-ilaç değildir), infüzyon biter bitmez pik yapar.",
    "endikasyon": "HAP/VAP, bakteriyemi/sepsis, komplike intraabdominal enfeksiyonlar; SSS enfeksiyonunda intratekal/intraventriküler; septik şokta hemoperfüzyon (Toraymyxin). Direnç gelişimini önlemek için genelde kombinasyon (yüksek doz Meropenem, Fosfomisin, Tigesiklin veya Rifampisin ile) tercih edilir.",
    "standartDoz": "Düşük/Standart Doz: 2.0-2.5 mg/kg (20.000-25.000 IU/kg) IV Yükleme (1 saatte)\nYüksek Doz: 1.25-1.5 mg/kg (12.500-15.000 IU/kg) q12h IV İdame (günlük toplam 2.5-3 mg/kg)",
    "renalDoz": "CrCl/HD/CRRT: Doz ayarı GEREKMEZ — idame dozu TBW ile aynı kalır (güncel konsensüs: Tsuji 2019 / IDSA / ESCMID / SCCM).\nNot: Böbrek yetmezliğinde doz düşürmek subterapötik düzeye ve direnç gelişimine yol açar; Polimiksin B ağırlıklı olarak böbrek dışı yolla elimine edildiği için klirens değişmez.\nKlasik tablo (artık önerilmiyor): CrCl >50: 1-1.25 mg/kg q12h; CrCl 20-50: 1 mg/kg q12h; CrCl 5-19: 0.5 mg/kg q12h; CrCl <5: 0.2 mg/kg q12h; CRRT: 0.5 mg/kg q12h.",
    "sinirlamalar": "Proteus spp., Serratia marcescens, Morganella morganii, Providencia spp., Burkholderia cepacia, tüm Gram-pozitifler ve anaeroblar doğal dirençlidir. İdrar yolu enfeksiyonunda (sistit/piyelonefrit) KULLANILMAZ — aktif ilaç idrarla neredeyse hiç atılmaz; İYE'de bunun yerine Kolistin tercih edilir.",
    "yanEtki": "Nöromüsküler blokaj (dirençli kas güçsüzlüğü, akut apne riski; Myastenia Gravis'te kontrendike), parestezi (yüz/ekstremitede, ~%27), baş-boyunda geri dönüşlü hiperpigmentasyon.",
    "nefroSeviye": "Orta",
    "nefroNot": "Css,avg >2 mg/L üzerinde ATN riski artar, genellikle geri dönüşlüdür; Kolistin'e göre belirgin şekilde daha az nefrotoksik kabul edilir.",
    "eliminasyon": "Esas olarak böbrek dışı (non-renal, hepatik/doku) metabolizma; idrarda değişmeden atılan aktif ilaç <%1 — renal fonksiyon ve diyalizden etkilenmez."
  },
  {
    "slug": "amikasin",
    "kategori": "POLİMİKSİNLER / AMİNOGLİKOZİTLER / TİGESİKLİN",
    "kategoriKisa": "Polimiksin / Aminoglikozit / Tigesiklin",
    "kategoriRenk": "amber",
    "grup": "Aminoglikozit",
    "etken": "Amikasin",
    "pazar": "Amikozit",
    "ozellikler": "Güçlü Gram-negatif aerob spektrum (Pseudomonas, Acinetobacter, dirençli enterik çomaklar).",
    "endikasyon": "Dirençli sepsislerde kombinasyon tedavisi, dirençli İYE, ampirik şok yönetimi.",
    "standartDoz": "Düşük Doz: 15 mg/kg q24h IV (Standart genişletilmiş aralıklı tek doz)\nYüksek Doz: 25-30 mg/kg q24h IV (Septik şokta pik düzey -Cmax- hedeflemesi, dirençli Pseudomonas/Acinetobacter kombinasyon tedavisi)",
    "renalDoz": "Genişletilmiş dozlamada:\nCrCl >50: Doz ayarı gerekmez (q24h).\nCrCl 30-50: Doz q48h'ye uzatılır.\nCrCl <30: Geleneksel bölünmüş dozlama (7.5 mg/kg q12h) ve TDM önerilir.",
    "sinirlamalar": "Anaerobik bakterilere ve asidik/hipoksik dokulara (apselere) nüfuz edemez, etkisizdir.",
    "yanEtki": "Nefrotoksisite (non-oligurik akut tübüler nekroz), irreversibl kohlear/vestibüler ototoksisite.",
    "nefroSeviye": "Yüksek",
    "nefroNot": "Çukur düzeyi >5-10 mcg/mL ise toksisite artar",
    "eliminasyon": "Renal (%90-99 glomerüler filtrasyonla idrardan)"
  },
  {
    "slug": "tigesiklin",
    "kategori": "POLİMİKSİNLER / AMİNOGLİKOZİTLER / TİGESİKLİN",
    "kategoriKisa": "Polimiksin / Aminoglikozit / Tigesiklin",
    "kategoriRenk": "amber",
    "grup": "Glisilsiklin",
    "etken": "Tigesiklin",
    "pazar": "Tygacil",
    "ozellikler": "Aşırı geniş Gram-pozitif/negatif spektrum; anaeroblar, MRSA, VRE, ESBL. Pseudomonas ve Proteus hariçtir.",
    "endikasyon": "Komplike intraabdominal enfeksiyonlar, ağır yumuşak doku enfeksiyonları, dirençli Acinetobacter sepsisi (kombinasyon içinde).",
    "standartDoz": "Düşük Doz: 100 mg IV Yükleme (stat), ardından 50 mg q12h IV\nYüksek Doz: 200 mg IV Yükleme (stat), ardından 100 mg q12h IV (Ağır dirençli enfeksiyonlarda)",
    "renalDoz": "Böbrek yetmezliğinde doz ayarlaması gerekmez.\nKaraciğer Yetmezliği: Child-Pugh C ise idame dozu 25 mg q12h IV'ye düşürülür.",
    "sinirlamalar": "Pseudomonas aeruginosa, Proteus türleri, Providencia ve Morganella morganii'ye karşı tamamen etkisizdir. Serum seviyesi düşük kaldığından bakteremi ve ürosepsiste tek başına kullanılmamalıdır.",
    "yanEtki": "Ciddi bulantı/kusma, koagülopati (hipofibrinojenemi, PT/aPTT uzaması), akut pankreatit (ölümcül olabilir).",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Biliyer/fekal atılım (%59), kısmen renal (%33)."
  },
  {
    "slug": "siprofloksasin",
    "kategori": "FLOROKİNOLONLAR & DİĞERLERİ",
    "kategoriKisa": "Florokinolon ve Diğerleri",
    "kategoriRenk": "green",
    "grup": "Florokinolon",
    "etken": "Siprofloksasin",
    "pazar": "Cipro, Sanset",
    "ozellikler": "Gram-negatif aeroblar (Pseudomonas dahil), atipik patojenler.",
    "endikasyon": "Komplike üriner sepsis, dirençli solunum yolu enfeksiyonları, intraabdominal enfeksiyonlar (kombine).",
    "standartDoz": "Düşük Doz: 400 mg q12h IV VEYA 500 mg q12h PO (Standart İYE veya solunum)\nYüksek Doz: 400 mg q8h IV VEYA 750 mg q12h PO (Ağır nozokomiyal pnömoni, dirençli Pseudomonas)",
    "renalDoz": "CrCl >30: Doz ayarı gerekmez.\nCrCl <=30: 200-400 mg q18-24h IV.\nHD/CRRT: 400 mg q24h IV.",
    "sinirlamalar": "Anaerobik bakterilere (B. fragilis vb.) ve MRSA'ya karşı etkisizdir.",
    "yanEtki": "QTc uzaması / Torsades de Pointes, nöbet eşiğini düşürme, tendon rüptürü riskleri.",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Böbrek (%40-50 idrarla), Kısmi Biliyer/Fekal"
  },
  {
    "slug": "levofloksasin",
    "kategori": "FLOROKİNOLONLAR & DİĞERLERİ",
    "kategoriKisa": "Florokinolon ve Diğerleri",
    "kategoriRenk": "green",
    "grup": "Florokinolon",
    "etken": "Levofloksasin",
    "pazar": "Tavanic, Kravit",
    "ozellikler": "Geniş Gram-pozitif, Gram-negatif aeroblar ve mükemmel atipik patojen etkinliği.",
    "endikasyon": "Toplum ve hastane kaynaklı pnömoni, lejyonella enfeksiyonları, komplike İYE.",
    "standartDoz": "Düşük Doz: 500 mg q24h IV/PO (Standart solunum, İYE)\nYüksek Doz: 500 mg q12h IV/PO VEYA 750 mg q24h IV (Ağır nozokomiyal pnömoni, VAP, dirençli pnömoni)",
    "renalDoz": "CrCl >=50: Doz ayarı gerekmez.\nCrCl 20-49: İlk gün 500-750 mg, sonra 250 mg q24h veya 500 mg q48h.\nCrCl <20: İlk gün 500-750 mg, sonra 250 mg q48h.",
    "sinirlamalar": "Anaerobik bakterilere zayıf etkilidir; MRSA'ya karşı monoterapi olarak önerilmez.",
    "yanEtki": "QTc uzaması, nörogirişimsel bozukluklar (özellikle yaşlılarda konfüzyon/halüsinasyon), tendon hasarı.",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Renal (%85 idrarla değişmeden atılır)"
  },
  {
    "slug": "metronidazol",
    "kategori": "FLOROKİNOLONLAR & DİĞERLERİ",
    "kategoriKisa": "Florokinolon ve Diğerleri",
    "kategoriRenk": "green",
    "grup": "Nitroimidazol",
    "etken": "Metronidazol",
    "pazar": "Nidazol, Flagyl",
    "ozellikler": "Tüm zorunlu anaerob bakteriler (B. fragilis, Clostridium türleri) ve protozoonlar.",
    "endikasyon": "İntraabdominal enfeksiyonlar (kombine), beyin absesi, Clostridioides difficile koliti, aspirasyon pnömonisi.",
    "standartDoz": "Düşük Doz: 500 mg q8h IV (veya 1 g q12h)\nYüksek Doz: 500 mg q6h IV veya 1.5 g q24h tek doz IV (Ağır nekrotizan intraabdominal enfeksiyonlar)",
    "renalDoz": "CrCl >10: Doz ayarı gerekmez.\nCrCl <10 (Ağır yetmezlik): Doz %50 azaltılır veya q12h uygulanır (aktif metabolit birikimini önlemek için).\nHD: Diyaliz sonrası ek doz verilmelidir.",
    "sinirlamalar": "Tüm aerobik Gram-pozitif ve Gram-negatif bakterilere karşı tamamen etkisizdir.",
    "yanEtki": "Periferik nöropati (uzun süreli kullanımda), metalik tat, disülfiram benzeri reaksiyon, nörotoksisite (konfüzyon, ensefalopati).",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Hepatik metabolizma (%60-80), renal (%60-80) ve fekal atılım."
  },
  {
    "slug": "flukonazol",
    "kategori": "ANTİFUNGALLER",
    "kategoriKisa": "Antifungaller",
    "kategoriRenk": "rose",
    "grup": "Triazol Antifungal",
    "etken": "Flukonazol",
    "pazar": "Triflucan, Zolax",
    "ozellikler": "Candida albicans, Candida tropicalis ve Cryptococcus neoformans.",
    "endikasyon": "Kandida sepsisi (duyarlı suşlarda), invaziv kandidiyaz profilaksisi.",
    "standartDoz": "Düşük Doz: 400 mg ilk gün yükleme, ardından 200 mg q24h IV/PO (Standart özofageal/idrar yolu)\nYüksek Doz: 800 mg ilk gün yükleme, ardından 400-800 mg q24h IV/PO (Kandidemi, invaziv kandidiyazis, Kriptokok menenjiti)",
    "renalDoz": "CrCl >50: Doz ayarı gerekmez.\nCrCl <=50: Yükleme sonrası idame dozları %50 azaltılarak uygulanır (100-200 mg q24h).\nHD/CRRT: Her diyaliz sonrası standart idame dozu uygulanır.",
    "sinirlamalar": "Candida krusei (doğal dirençli), Candida glabrata (genelde doz bağımlı dirençli) ve Aspergillus türlerine KESİNLİKLE etkisizdir.",
    "yanEtki": "Karaciğer enzimlerinde (ALT/AST) yükseklik, QTc uzaması, döküntü.",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Renal (%80 idrarla değişmeden atılır)"
  },
  {
    "slug": "vorikonazol",
    "kategori": "ANTİFUNGALLER",
    "kategoriKisa": "Antifungaller",
    "kategoriRenk": "rose",
    "grup": "Geniş Spektrumlu Triazol",
    "etken": "Vorikonazol",
    "pazar": "Vfend",
    "ozellikler": "Aspergillus türleri, Candida glabrata ve krusei dahil dirençli Kandidalar.",
    "endikasyon": "İnvaziv aspergilloz (altın standart), ağır fungal sepsis yönetimi.",
    "standartDoz": "IV Yükleme: 6 mg/kg q12h (ilk 24 saat), IV İdame: 4 mg/kg q12h (PO: 200 mg q12h)",
    "renalDoz": "Oral Vorikonazol için renal doz ayarı gerekmez. Ancak:\nCrCl <50 ise IV formun taşıyıcısı olan SBECD böbrekte biriktiği için IV FORM KULLANILMAMALI, hasta ORAL forma geçirilmelidir.\nKaraciğer Yetmezliği (Hafif-Orta): İdame dozu %50 azaltılır.",
    "sinirlamalar": "Zygomycetes (Mucor vb.) türlerine karşı tamamen etkisizdir.",
    "yanEtki": "Geçici görsel bozukluklar (%30, parlaklık artışı vb.), karaciğer toksisitesi, döküntü, halüsinasyonlar.",
    "nefroSeviye": "Orta",
    "nefroNot": "IV formdaki taşıyıcı madde nedeniyle renal risk",
    "eliminasyon": "Hepatik (CYP2C19, CYP2C9 ve CYP3A4 üzerinden yoğun metabolizma)"
  },
  {
    "slug": "kaspofungin",
    "kategori": "ANTİFUNGALLER",
    "kategoriKisa": "Antifungaller",
    "kategoriRenk": "rose",
    "grup": "Ekinokandin",
    "etken": "Kaspofungin",
    "pazar": "Cancidas",
    "ozellikler": "Mükemmel tüm Candida türleri (glabrata/krusei dahil) ve Aspergillus.",
    "endikasyon": "YBÜ ampirik antifungal tedavisi (şoktaki hastalarda ilk tercih), invaziv kandidiyazis.",
    "standartDoz": "Düşük Doz: 70 mg Yükleme, ardından 50 mg q24h IV (Kilo <80 kg olan standart hasta)\nYüksek Doz: 70 mg Yükleme, ardından 70 mg q24h IV (Ağır fungal sepsis/şok veya hasta kilosu >80 kg ise)",
    "renalDoz": "Böbrek yetmezliğinde doz ayarlaması gerekmez (CRRT dahil).\nKaraciğer Yetmezliği (Child-Pugh B): İdame dozu 35 mg q24h'ye düşürülmelidir.",
    "sinirlamalar": "Cryptococcus neoformans ve Mucorales türlerine karşı tamamen etkisizdir.",
    "yanEtki": "Hipoalbüminemi, karaciğer enzimlerinde yükselme, infüzyon ilişkili histamin deşarjı.",
    "nefroSeviye": "Düşük",
    "nefroNot": "",
    "eliminasyon": "Hepatik metabolizma (böbrekten minimal atılım)"
  },
  {
    "slug": "lipozomal-amfoterisin-b",
    "kategori": "ANTİFUNGALLER",
    "kategoriKisa": "Antifungaller",
    "kategoriRenk": "rose",
    "grup": "Poliyen Antifungal",
    "etken": "Lipozomal Amfoterisin B",
    "pazar": "Ambisome",
    "ozellikler": "Neredeyse tüm patojen mantarlar (Aspergillus, Candida, Mucor, Cryptococcus).",
    "endikasyon": "Dirençli fungal sepsisler, invaziv mukormikoz (ilk tercih), şüpheli kandidiyaz.",
    "standartDoz": "Düşük Doz: 3 mg/kg q24h IV (Standart aspergilloz, kandidiyazis, febril nötropeni)\nYüksek Doz: 5-10 mg/kg q24h IV (Mukormikozis, santral sinir sistemi fungal enfeksiyonları, ağır yaygın fungal sepsisler)",
    "renalDoz": "Böbrek yetmezliğinde doz ayarlaması gerekmez.\nAncak ciddi nefrotoksisite riski nedeniyle böbrek fonksiyonları, potasyum ve magnezyum düzeyleri günlük takip edilmelidir.\nCRRT: Doz ayarı gerekmez.",
    "sinirlamalar": "Neredeyse hiçbir dirençli mantarda etkisiz değildir, ancak ciddi sistemik toksisite sınırlandırıcıdır.",
    "yanEtki": "Ağır nefrotoksisite (tübüler asidoz, K/Mg kaybı), infüzyon ilişkili reaksiyonlar (titreme, ateş, rigor).",
    "nefroSeviye": "Yüksek",
    "nefroNot": "Konvansiyonel forma göre daha düşük ama ICU'da hala yüksektir",
    "eliminasyon": "Hepatik ve Renal dışı (Yarı ömrü çok uzundur, dokularda birikir)"
  }
];
